Snsproject/Snsproject/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls'), name='main'),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('', views.index, name='index'),


]

Snsproject/accounts/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

app_name = "accounts"
urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("delete/", views.delete, name="delete"),
]

Snsproject/main/urls.py
from django.urls import path, include
from . import views

app_name = "main"
urlpatterns = [
    path("calendar/", views.showcalendar, name="calendar"),
    path("chart/", views.chart, name="chart"),
    path("recommend/", views.reco_music, name="recommend"),
    path("analysis/", views.analysis, name="analysis"),
    path("<int:pk>", views.detail, name="detail"),
]

Snsproject/main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Posting(models.Model):
    insta = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.TextField(verbose_name="게시글")
    emotion = models.CharField(max_length=30, verbose_name="감정정보", null=True)
    pub_date = models.DateField()

    def __str__(self):
        return "%s %s" % (self.insta, self.emotion)

    def get_absolute_url(self):
        url = reverse("main:detail", args=[str(self.id)])
        return f'<a href="%s">' % (url)


class MusicBox(models.Model):
    emoti = models.CharField(max_length=30, verbose_name="emotion name")
    m_name = models.CharField(max_length=100, verbose_name="music name")
    m_artist = models.CharField(max_length=100, verbose_name="music artist")
    url = models.URLField("URL", unique=True)

    def __str__(self):
        return "%s %s" % (self.emoti, self.music)

Snsproject/main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import MusicBox, Posting
from django.contrib.auth.models import User
from django.utils.safestring import mark_safe
from django.http import HttpResponse, HttpResponseRedirect
from .utils import Calendar
import datetime
import calendar
import random
from dateutil.relativedelta import relativedelta
from django.utils import timezone
from django.contrib import auth
from .apps import MainConfig

# 캘린더


def showcalendar(request):
    today = get_date(request.GET.get("month", None))
    userr_id = request.session.get("user1")
    prev_month_var = prev_month(today)
    next_month_var = next_month(today)

    cal = Calendar(today.year, today.month)
    html_cal = cal.formatmonth(userr_id, withyear=True)
    result_cal = mark_safe(html_cal)

    context = {
        "calendar": result_cal,
        "prev_month": prev_month_var,
        "next_month": next_month_var,
    }

    return render(request, "main/calendar.html", context)


def get_date(req_day):
    if req_day:
        year, month = (int(x) for x in req_day.split("-"))
        return datetime.date(year, month, day=1)
    return datetime.datetime.today()


def prev_month(day):
    first = day.replace(day=1)
    prev_month = first - datetime.timedelta(days=1)
    month = "month=" + str(prev_month.year) + "-" + str(prev_month.month)
    return month


def next_month(day):
    days_in_month = calendar.monthrange(day.year, day.month)[1]
    last = day.replace(day=days_in_month)
    next_month = last + datetime.timedelta(days=1)
    month = "month=" + str(next_month.year) + "-" + str(next_month.month)
    return month


# 모델 코드
def analysis(request):
    userr_id = request.session.get("user1")
    co = 0
    if userr_id:
        date = (
            Posting.objects.filter(insta=userr_id)
            .values_list("pub_date", flat=True)
            .distinct()
        )
        for i in date:
            oone_post = (Posting.objects.filter(
                insta=userr_id).filter(pub_date=i))
            one_post = oone_post.first()
            sentences = one_post.post
            logitt = MainConfig.modelss
            logit = logitt.emotionR(sentences)
            one_post.emotion = logit
            one_post.save()
    return render(request, "main/analysis.html")


def emoti_count(emoti):
    emoti1, emoti2, emoti3, emoti4, emoti5, emoti6 = 0, 0, 0, 0, 0, 0
    data = []
    for x in emoti:
        if x.emotion == "0":
            emoti1 += 1
        if x.emotion == "1":
            emoti2 += 1
        if x.emotion == "2":
            emoti3 += 1
        if x.emotion == "3":
            emoti4 += 1
        if x.emotion == "4":
            emoti5 += 1
        if x.emotion == "5":
            emoti6 += 1

    data = [emoti1, emoti2, emoti3, emoti4, emoti5, emoti6]
    return data


def chart(request):
    userr_id = request.session.get("user1")
    labels = ["anger", "fear", "joy", "love", "sadness", "suprise"]
    now = timezone.now()
    lastmonth = now - relativedelta(months=1)
    emoti = Posting.objects.exclude(
        pub_date__gte=now).filter(pub_date__gte=lastmonth).filter(insta=userr_id)

    data = []
    data = emoti_count(emoti)
    context = {"labels": labels, "data": data,
               "now": now, "lastmonth": lastmonth}
    return render(request, "main/chart.html", context)
# 컨텐츠 추천


def reco_music(request):
    userr_id = request.session.get("user1")
    now = timezone.now()
    lastmonth = now - relativedelta(months=1)
    emoti = Posting.objects.exclude(
        pub_date__gte=now).filter(pub_date__gte=lastmonth).filter(insta=userr_id)

    data = []
    data = emoti_count(emoti)
    max = data[0]
    for i in range(0, 6):
        if data[i] > max:
            max = data[i]
            maxemoti = i

    if maxemoti == 0:
        musics = list(MusicBox.objects.filter(emoti__contains="anger"))
        musics = random.sample(musics, 3)
        emot = "anger"
    elif maxemoti == 4:
        musics = list(MusicBox.objects.filter(emoti__contains="sadness"))
        emot = "sadness"
        musics = random.sample(musics, 3)
    elif maxemoti == 1:
        musics = list(MusicBox.objects.filter(emoti__contains="fear"))
        emot = "fear"
        musics = random.sample(musics, 3)
    elif maxemoti == 3:
        musics = list(MusicBox.objects.filter(emoti__contains="love"))
        emot = "love"
        musics = random.sample(musics, 3)
    elif maxemoti == 5:
        musics = list(MusicBox.objects.filter(emoti__contains="suprise"))
        emot = "suprise"
        musics = random.sample(musics, 3)
    elif maxemoti == 2:
        musics = list(MusicBox.objects.filter(emoti__contains="joy"))
        emot = "joy"
        musics = random.sample(musics, 3)

    context = {"emot": emot, "musics": musics}
    return render(request, "main/recommend.html", context)


def detail(request, pk):
    post_detail = get_object_or_404(Posting, pk=pk)
    return render(request, 'main/detail.html', {'posts': post_detail})

Snsproject/main/templates/main/analysis.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="/static/main/css/login.css">
    <title>analysis</title>
</head>
<body>
    <div class=wrap>
        <div style=height:20px;></div>
        <div class=content01>
            <div class=back>
    {% if user.is_authenticated %}
    <br><br><br><br>
    <div class="loader" style=margin-left:50px;></div>
    <div class="menu">
        
        <h4>&nbsp;&nbsp;{{request.user.username}}님의 감정분석 중...</h4>
    </div>
    {% endif %}
    <div>
        &nbsp;&nbsp;

        <button type="button" class="submit-btn" 
        onclick="location.href='/main/calendar/'">결과보기</button>
        </div>
       
    </div>
    </div>
    </div>
</body>
</html>

Snsproject/main/templates/main/calendar.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <!--
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css"> 
  -->
  <link rel="stylesheet" type="text/css" href="/static/main/css/chart.css">
  <script src="https://kit.fontawesome.com/b5ddf8349a.js" crossorigin="anonymous"></script>
  <title>emotion calendar</title>
   
</head>

<body>
<div class = back>
   <div class=wrap>
      <div class=menu_left>
          <div class=logo></div>
          {% if user.is_authenticated %}
          <div class=insta_id>
             <h4>{{request.user.username}}</h4>
            </div>
          {% else %}
          <div class=insta_id><h4><a href="{% url 'accounts:login' %}">로그인</a></h4></div>
          {% endif %}
          <nav id=navmenu>
            <ul>
               <li>😍love</li>
               <li>😆joy</li> 
               <li>😳surprise</li>
               <li>😡angry</li>
               <li>😭sadness</li>  
               <li>😱fear</li>
            </ul>
          </nav>
       </div>
       <div class=content>
          <div class=title>
              <div class="prev"><a  href="{% url 'main:calendar' %}?{{ prev_month }}"><i class="fas fa-arrow-alt-circle-left"></i></a></div>
              <div class="sub_title"><h2>&nbsp;EMOTION CALENDAR&nbsp;&nbsp;</h2></div>
              <div class="next"><a  href="{% url 'main:calendar' %}?{{ next_month }}"><i class="fas fa-arrow-alt-circle-right"></i></a></div>
          </div>
          <div class=main>
             {{ calendar }}
         </tr></table>
         </div>
      </div>
       <div class=menu_right>
         <nav id=navmenu2>
            <ul>
               <li><a href="{% url 'main:calendar' %}"><i class="fas fa-calendar-alt"></i> Calendar</a></li>
               <li><a href="{% url 'main:chart' %}"><i class="fas fa-chart-pie"></i> Chart</a></li>
               <li><a href="{% url 'main:recommend' %}"><i class="fas fa-icons"></i> Recommend</a></li>
               {% if user.is_authenticated %}
               <li><a href="{% url 'accounts:logout' %}"><i class="fas fa-sign-out-alt"></i> Log Out</a></li>
               <br><br><br><br><br><br><br><br><br><br><br>
               <li><a href="{% url 'accounts:delete' %}"><i class="fas fa-user-times"></i> Sign out</a></li>
               {% endif %}  
            </ul>
         </nav>
       </div>
  </div>
</div>   

</body>
</html>

Snsproject/main/templates/main/chart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.min.js"></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"></script>
    <script src="https://kit.fontawesome.com/b5ddf8349a.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="/static/main/css/chart.css">
    <title>emotion chart</title>
    
</head>
<body>
<div class = wrap> 
    <div class=wrap>
        <div class=menu_left>
            <div class=logo></div>
            {% if user.is_authenticated %}
            <div class=insta_id>
               <h4>{{request.user.username}}</h4>
              </div>
            {% else %}
            <div class=insta_id><h4><a href="{% url 'accounts:login' %}">로그인</a></h4></div>
            {% endif %}
            <nav id=navmenu>
               <ul>
                  <li>😍love</li>
                  <li>😆joy</li> 
                  <li>😳surprise</li>
                  <li>😡angry</li>
                  <li>😭sadness</li>  
                  <li>😱fear</li>
               </ul>
            </nav>
         </div>
         <div class=content>
            <div class=title>
                <div class="sub_title"><h2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    EMOTION CHART</h2></div>
            </div>
            <div class=main>
                <div id=chart align=center> 
                    <canvas id="myChart" width="380" height="380"></canvas>  
                </div>
            </div>
        </div>
         <div class=menu_right>
            <nav id=navmenu2>
               <ul>
                  <li><a href="{% url 'main:calendar' %}"><i class="fas fa-calendar-alt"></i> Calendar</a></li>
                  <li><a href="{% url 'main:chart' %}"><i class="fas fa-chart-pie"></i> Chart</a></li>
                  <li><a href="{% url 'main:recommend' %}"><i class="fas fa-icons"></i> Recommend</a></li>
                  {% if user.is_authenticated %}
                  <li><a href="{% url 'accounts:logout' %}"><i class="fas fa-sign-out-alt"></i> Log Out</a></li>
                  <br><br><br><br><br><br><br><br><br><br><br>
                  <li><a href="{% url 'accounts:delete' %}"><i class="fas fa-user-times"></i> Sign out</a></li>
                  {% endif %}  
                </ul>
            </nav>
         </div>
    </div>
    
<script>
var ctx = document.getElementById('myChart').getContext('2d');
var  emotion_labels={{labels|safe}};
var  emotion_datas={{data|safe}};
var myChart = new Chart(ctx, {
    type: 'line',
    data: {
        labels: emotion_labels,
        datasets: [{
            label: 'emotion statistics',
            data: emotion_datas,
            backgroundColor: [
                'rgba(255, 102, 102, 0.3)',
                'rgba(255, 255, 51, 0.3)',
                'rgba(255, 128, 0, 0.3)',
                'rgba(75, 192, 192, 0.3)',
                'rgba(0, 0, 255, 0.3)',
                'rgba(51, 251, 51, 0.3)'
            ],
            borderColor : [
                'rgba(255, 102, 102, 1)',
                'rgba(255, 255, 51, 1)',
                'rgba(255, 128, 0, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(0, 0, 255, 1)',
                'rgba(51, 251, 51, 1)'
            ],
            borderWidth : 1
        }]
    },
    options: {
        responsive:false,
        scales: {
            y: {
                beginAtZero: true
            }
        },
    }
});
</script>

</div>
</body>
</html>

Snsproject/main/templates/main/detail.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <!--
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css"> 
  -->
  <link rel="stylesheet" type="text/css" href="/static/main/css/chart.css">
  <script src="https://kit.fontawesome.com/b5ddf8349a.js" crossorigin="anonymous"></script>
  <title>post detail</title>
   
</head>

<body>
<div class = back>
   <div class=wrap>
      <div class=menu_left>
          <div class=logo></div>
          {% if user.is_authenticated %}
          <div class=insta_id>
             <h4>{{request.user.username}}</h4>
            </div>
          {% else %}
          <div class=insta_id><h4>로그인</h4></div>
          {% endif %}
          <nav id=navmenu>
            <ul>
               <li>😍love</li>
               <li>😆joy</li> 
               <li>😳surprise</li>
               <li>😡angry</li>
               <li>😭sadness</li>  
               <li>😱fear</li>
            </ul>
          </nav>
       </div>
       <div class=content>
          <div class=title>
              <div class="sub_title"><h2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
               &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  
               POST</h2></div>
          </div>
          <div class=main>
             <div class=text01><p>{{posts.post}}</p></div>
           
             <button type="button" class="submit-btn" 
             onclick="location.href='/main/calendar/'"><i class="fas fa-undo-alt"></i></button>
         </tr></table>
         </div>
      </div>
       <div class=menu_right>
         <nav id=navmenu2>
            <ul>
               <li><a href="{% url 'main:calendar' %}"><i class="fas fa-calendar-alt"></i> Calendar</a></li>
               <li><a href="{% url 'main:chart' %}"><i class="fas fa-chart-pie"></i> Chart</a></li>
               <li><a href="{% url 'main:recommend' %}"><i class="fas fa-icons"></i> Recommend</a></li>
               {% if user.is_authenticated %}
               <li><a href="{% url 'accounts:logout' %}"><i class="fas fa-sign-out-alt"></i> Log Out</a></li>
               <br><br><br><br><br><br><br><br><br><br><br>
               <li><a href="{% url 'accounts:delete' %}"><i class="fas fa-user-times"></i> Sign out</a></li>
               {% endif %}  
            </ul>
         </nav>
       </div>
  </div>
</div>   
</body>
</html>

Snsproject/main/templates/main/recommend.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/b5ddf8349a.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="/static/main/css/chart.css">
    <title>recommend music</title>
</head>
<body>
<div class = back> 
    <div class=wrap>
        <div class=menu_left>
            <div class=logo></div>
            {% if user.is_authenticated %}
          <div class=insta_id>
             <h4>{{request.user.username}}</h4>
            </div>
          {% else %}
          <div class=insta_id><h4><a href="{% url 'accounts:login' %}">로그인</a></h4></div>
          {% endif %}
            <nav id=navmenu>
               <ul>
                  <li>😍love</li>
                  <li>😆joy</li> 
                  <li>😳surprise</li>
                  <li>😡angry</li>
                  <li>😭sadness</li>  
                  <li>😱fear</li>
               </ul>
            </nav>
         </div>
         <div class=content>
            <div class=title>
                <div class="sub_title"><h2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;EMOTION RECOMMEND</h2></div>
            </div>
            <div class=main>
                {% block content %}
                <br><br>
                <div id='font'>{{emot}} 감정에 이 음악을 추천합니다.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div>
                <div id='font'>이모티콘을 클릭하면 들을 수 있습니다!&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</div>
                <br><br> <br><br>
                {% for musicname in musics  %}
                    <li id="music"><a href="{{musicname.url}}"><i class="fas fa-drum"></i></a></li>
                {% endfor %}    
                {% endblock %}   
            </div>
        </div>
        <div class=menu_right>
            <nav id=navmenu2>
               <ul>
                  <li><a href="{% url 'main:calendar' %}"><i class="fas fa-calendar-alt"></i> Calendar</a></li>
                  <li><a href="{% url 'main:chart' %}"><i class="fas fa-chart-pie"></i> Chart</a></li>
                  <li><a href="{% url 'main:recommend' %}"><i class="fas fa-icons"></i> Recommend</a></li>
                  {% if user.is_authenticated %}
                  <li><a href="{% url 'accounts:logout' %}"><i class="fas fa-sign-out-alt"></i> Log Out</a></li>
                  <br><br><br><br><br><br><br><br><br><br><br>
                  <li><a href="{% url 'accounts:delete' %}"><i class="fas fa-user-times"></i> Sign out</a></li>
                  {% endif %}  
               </ul>
            </nav>
         </div>
    </div>
</div>
</body>
</html>